services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - voice_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/.venv
      - ./frontend:/frontend
    depends_on:
      - mongo
    networks:
      - voice_net

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "backend:5001"
      - "--domain=january-laundry-devotion.ngrok-free.dev"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - backend
    networks:
      - voice_net

volumes:
  mongo_data:

networks:
  voice_net:
    driver: bridge
